<?php
require_once __DIR__ . '/../src/behavior/fly/IFlyBehavior.php';
require_once __DIR__ . '/../src/behavior/fly/FlyWithWings.php';
require_once __DIR__ . '/../src/behavior/fly/FlyNoWay.php';
require_once __DIR__ . '/../src/behavior/quack/IQuackBehavior.php';
require_once __DIR__ . '/../src/behavior/quack/QuackBehavior.php';
require_once __DIR__ . '/../src/behavior/quack/SqueakBehavior.php';
require_once __DIR__ . '/../src/behavior/quack/MuteQuackBehavior.php';
require_once __DIR__ . '/../src/behavior/dance/IDanceBehavior.php';
require_once __DIR__ . '/../src/behavior/dance/NoDanceBehavior.php';
require_once __DIR__ . '/../src/behavior/dance/WaltzDanceBehavior.php';
require_once __DIR__ . '/../src/behavior/dance/MinuetDanceBehavior.php';
require_once __DIR__ . '/../src/duck/Duck.php';
require_once __DIR__ . '/../src/duck/DecoyDuck.php';
require_once __DIR__ . '/../src/duck/RedheadDuck.php';
require_once __DIR__ . '/../src/duck/RubberDuck.php';
require_once __DIR__ . '/../src/duck/MallardDuck.php';
require_once __DIR__ . '/../src/duck/ModelDuck.php';
require_once __DIR__ . '/../src/SimUDuck.php';